name: draugmedia
favicon: null
layout_spectrum: 0.3935587469022721
typography_spectrum: 0.8384040971286595
title: draugmedia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e16824'
    - '#d9e1eb'
    - '#009ea5'
    - '#ff001d'
    - '#4b4a47'
  brandStrength: 0.5
  lightness: 0.9040960455313325
  saturation: 0.7187139319721609
  rhythmicContrast: 0.48588319798000157
purpose: []
