name: draugmedia
favicon: null
layout_spectrum: 0.9354
typography_spectrum: 0.94192
title: draugmedia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f8f8'
    - '#000000'
    - '#c76814'
    - '#619aa9'
    - '#f838c1'
  brandStrength: 0.6875
  lightness: 0.9040960455313325
  saturation: 0.7187139319721609
  rhythmicContrast: 0.25
purpose: []
