name: draugmedia
favicon: null
layout_spectrum: 0.3935587469022721
typography_spectrum: 0.8384040971286595
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.35506623168475926
  lightness: 0.9040960455313325
  saturation: 0.7187139319721609
  rhythmicContrast: 0.48588319798000157
purpose: []
