layout_spectrum: 0.6935881318058819
typography_spectrum: 0.38741458021104336
color:
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
  brandStrength: 0.11009616078808904
  lightness: 0.06829794100485742
  saturation: 0.17425294127315283
  rhythmicContrast: 0.5680172587744892
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: draugmedia
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: draugmedia
description: music nonstop
purpose: []
